version: '3.7'
services:
  ### Product service
  db-product:
    container_name: db-product
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_product
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources